[2025-03-05T03:00:05.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T03:00:05.880+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-03-04T03:00:00+00:00 [queued]>
[2025-03-05T03:00:05.890+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-03-04T03:00:00+00:00 [queued]>
[2025-03-05T03:00:05.890+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-05T03:00:05.912+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-03-04 03:00:00+00:00
[2025-03-05T03:00:05.916+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14487) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-05T03:00:05.924+0000] {standard_task_runner.py:72} INFO - Started process 14488 to run task
[2025-03-05T03:00:05.923+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'scheduled__2025-03-04T03:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmp_4ipbbu5']
[2025-03-05T03:00:05.925+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask execute_training
[2025-03-05T03:00:06.094+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training scheduled__2025-03-04T03:00:00+00:00 [running]> on host 90a85505a05d
[2025-03-05T03:00:06.304+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='datamasterylab.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T03:00:00+00:00'
[2025-03-05T03:00:06.306+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T03:00:10.948+0000] {warnings.py:112} WARNING - /opt/***/dags/fraud_detection_training.py:15: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import astype

[2025-03-05T03:00:11.139+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training
[2025-03-05T03:00:11.147+0000] {fraud_detection_training.py:59} INFO - Configuration loaded successfully
[2025-03-05T03:00:11.327+0000] {fraud_detection_training.py:84} INFO - Minio connection verified. Buckets: ['mlflow']
[2025-03-05T03:00:11.786+0000] {fraud_detection_training.py:171} INFO - Starting model training process
[2025-03-05T03:00:11.787+0000] {fraud_detection_training.py:97} INFO - Connecting to kafka topic transactions
[2025-03-05T03:00:11.825+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.169.210.18', 9092)]>: connecting to pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.169.210.18', 9092) IPv4]
[2025-03-05T03:00:11.827+0000] {conn.py:1219} INFO - Probing node bootstrap-0 broker version
[2025-03-05T03:00:11.843+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.169.210.18', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:12.013+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.210.18', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:12.014+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.169.210.18', 9092)]>: Connection complete.
[2025-03-05T03:00:12.130+0000] {conn.py:1282} INFO - Broker version identified as 2.6.0
[2025-03-05T03:00:12.131+0000] {conn.py:1283} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-03-05T03:00:12.134+0000] {consumer.py:118} WARNING - group_id is None: disabling auto-commit.
[2025-03-05T03:00:12.134+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('transactions',)
[2025-03-05T03:00:12.144+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('transactions', 0), ('transactions', 1), ('transactions', 2), ('transactions', 3), ('transactions', 4), ('transactions', 5)]
[2025-03-05T03:00:12.162+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.41.38.144', 9092)]>: connecting to b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('13.41.38.144', 9092) IPv4]
[2025-03-05T03:00:12.276+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.41.38.144', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:12.651+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.41.38.144', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:12.652+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.41.38.144', 9092)]>: Connection complete.
[2025-03-05T03:00:12.653+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=bootstrap-0 host=pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.169.210.18', 9092)]>: Closing connection. 
[2025-03-05T03:00:12.791+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('18.135.141.220', 9092)]>: connecting to b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('18.135.141.220', 9092) IPv4]
[2025-03-05T03:00:12.902+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('18.135.141.220', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:13.372+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.135.141.220', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:13.376+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('18.135.141.220', 9092)]>: Connection complete.
[2025-03-05T03:00:13.506+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.43.33.231', 9092)]>: connecting to b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('13.43.33.231', 9092) IPv4]
[2025-03-05T03:00:13.613+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.43.33.231', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:14.044+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.43.33.231', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:14.044+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.43.33.231', 9092)]>: Connection complete.
[2025-03-05T03:00:14.178+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('51.24.25.161', 9092)]>: connecting to b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('51.24.25.161', 9092) IPv4]
[2025-03-05T03:00:14.292+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('51.24.25.161', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:14.761+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('51.24.25.161', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:14.762+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('51.24.25.161', 9092)]>: Connection complete.
[2025-03-05T03:00:14.895+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('3.8.72.118', 9092)]>: connecting to b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('3.8.72.118', 9092) IPv4]
[2025-03-05T03:00:15.007+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('3.8.72.118', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:15.483+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.8.72.118', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:15.486+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.8.72.118', 9092)]>: Connection complete.
[2025-03-05T03:00:15.634+0000] {conn.py:384} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('3.11.225.156', 9092)]>: connecting to b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 [('3.11.225.156', 9092) IPv4]
[2025-03-05T03:00:15.748+0000] {conn.py:480} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('3.11.225.156', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-03-05T03:00:16.194+0000] {conn.py:665} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.225.156', 9092)]>: Authenticated as XGISOSVJLGK43N6I via PLAIN
[2025-03-05T03:00:16.194+0000] {conn.py:449} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('3.11.225.156', 9092)]>: Connection complete.
[2025-03-05T03:00:31.297+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.41.38.144', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.301+0000] {fetcher.py:782} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=1 host=b1-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.41.38.144', 9092)]>
[2025-03-05T03:00:31.302+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.135.141.220', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.302+0000] {fetcher.py:782} INFO - Fetch to node 4 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=4 host=b4-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('18.135.141.220', 9092)]>
[2025-03-05T03:00:31.303+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.43.33.231', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.303+0000] {fetcher.py:782} INFO - Fetch to node 2 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=2 host=b2-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.43.33.231', 9092)]>
[2025-03-05T03:00:31.303+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('51.24.25.161', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.305+0000] {fetcher.py:782} INFO - Fetch to node 5 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=5 host=b5-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('51.24.25.161', 9092)]>
[2025-03-05T03:00:31.305+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.8.72.118', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.307+0000] {fetcher.py:782} INFO - Fetch to node 3 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=3 host=b3-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.8.72.118', 9092)]>
[2025-03-05T03:00:31.307+0000] {conn.py:928} INFO - <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.225.156', 9092)]>: Closing connection. 
[2025-03-05T03:00:31.308+0000] {fetcher.py:782} INFO - Fetch to node 0 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.5, node_id=0 host=b0-pkc-41wq6.eu-west-2.aws.confluent.cloud:9092 <connected> [IPv4 ('3.11.225.156', 9092)]>
[2025-03-05T03:00:32.715+0000] {fraud_detection_training.py:125} INFO - Kafka data read successfully with fraud rate: 0.38%
[2025-03-05T03:00:39.984+0000] {fraud_detection_training.py:250} INFO - Starting hyperparameter tuning...
[2025-03-05T03:00:39.990+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-03-05T03:03:24.521+0000] {fraud_detection_training.py:254} INFO - Best hyperparameters: {'classifier__subsample': 0.6, 'classifier__reg_alpha': 0, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1, 'classifier__gamma': 0, 'classifier__colsample_bytree': 0.6}
[2025-03-05T03:03:25.037+0000] {fraud_detection_training.py:260} INFO - Optimal threshold determined: 0.7038
[2025-03-05T03:03:26.755+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-03-05T03:03:27.855+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2025-03-05T03:03:34.856+0000] {logging_mixin.py:190} WARNING - Registered model 'fraud_detection_model' already exists. Creating a new version of this model...
[2025-03-05T03:03:35.007+0000] {logging_mixin.py:190} WARNING - 2025/03/05 03:03:35 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: fraud_detection_model, version 5
[2025-03-05T03:03:35.007+0000] {logging_mixin.py:190} WARNING - Created version '5' of model 'fraud_detection_model'.
[2025-03-05T03:03:35.168+0000] {fraud_detection_training.py:322} INFO - Training successfully completed with metrics: {'auc_pr': 0.40981776619559507, 'precision': 0.8, 'recall': 0.3851851851851852, 'f1': 0.52, 'threshold': 0.7037914991378784}
[2025-03-05T03:03:35.242+0000] {logging_mixin.py:190} INFO - 🏃 View run debonair-croc-801 at: http://mlflow-server:5500/#/experiments/1/runs/37916f9a380f4d5588bc21021603b48e
[2025-03-05T03:03:35.243+0000] {logging_mixin.py:190} INFO - 🧪 View experiment at: http://mlflow-server:5500/#/experiments/1
[2025-03-05T03:03:35.363+0000] {python.py:240} INFO - Done. Returned value was: {'status': 'success', 'precision': {'auc_pr': 0.40981776619559507, 'precision': 0.8, 'recall': 0.3851851851851852, 'f1': 0.52, 'threshold': 0.7037914991378784}}
[2025-03-05T03:03:35.488+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T03:03:35.488+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=execute_training, run_id=scheduled__2025-03-04T03:00:00+00:00, execution_date=20250304T030000, start_date=20250305T030005, end_date=20250305T030335
[2025-03-05T03:03:35.681+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T03:03:35.776+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T03:03:35.782+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
