[2025-03-03T23:51:54.094+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T23:51:54.163+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.validate_environment manual__2025-03-03T23:51:51.348530+00:00 [queued]>
[2025-03-03T23:51:54.173+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.validate_environment manual__2025-03-03T23:51:51.348530+00:00 [queued]>
[2025-03-03T23:51:54.173+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-03T23:51:54.200+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): validate_environment> on 2025-03-03 23:51:51.348530+00:00
[2025-03-03T23:51:54.205+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5710) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-03T23:51:54.207+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'validate_environment', 'manual__2025-03-03T23:51:51.348530+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmp6ih9f66a']
[2025-03-03T23:51:54.209+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask validate_environment
[2025-03-03T23:51:54.209+0000] {standard_task_runner.py:72} INFO - Started process 5711 to run task
[2025-03-03T23:51:54.348+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.validate_environment manual__2025-03-03T23:51:51.348530+00:00 [running]> on host b7f28f610775
[2025-03-03T23:51:54.575+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='datamasterylab.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='validate_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T23:51:51.348530+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T23:51:51.348530+00:00'
[2025-03-03T23:51:54.576+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T23:51:54.620+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-03T23:51:54.621+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        echo "Validating environment..."\n        test -f /app/config.yaml &&\n        test -f /app/.env && \n        echo "Environment is valid!"\n        ']
[2025-03-03T23:51:54.630+0000] {subprocess.py:99} INFO - Output:
[2025-03-03T23:51:54.653+0000] {subprocess.py:106} INFO - Validating environment...
[2025-03-03T23:51:54.655+0000] {subprocess.py:106} INFO - Environment is valid!
[2025-03-03T23:51:54.656+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-03T23:51:54.769+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T23:51:54.770+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=validate_environment, run_id=manual__2025-03-03T23:51:51.348530+00:00, execution_date=20250303T235151, start_date=20250303T235154, end_date=20250303T235154
[2025-03-03T23:51:54.922+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T23:51:55.002+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T23:51:55.007+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
